name: ci

on:
  push:
    branches:
      - 'dev'

jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v2
      -
        name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Merge dev to master
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          branch: master
          base: dev
          title: '[AUTO] Merge'
          labels: |
            automerge