name: ci

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to ECR
        uses: docker/login-action@v1
        run: sudo apt-get install -y crudini
        with:
          registry: ${crudini --get fargate1/config.ini Docker image}
          sername: ${crudini --get fargate1/config.ini AWS access_key}
          password: ${crudini --get fargate1/config.ini AWS secret}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: fargate1/
          file: fargate1/Dockerfile
          push: true
          tags: user/app:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}