name: cd

on:
  push:
    branches:
      - 'master'

jobs:
  docker-database:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout repository
        uses: actions/checkout@v2
      -
        name: Add crudini
        run: |
          sudo apt-get install -y crudini
          echo "P_DOCKER_IMAGE=$(crudini --get fargate2/config.ini Docker image)" >> $GITHUB_ENV
          echo "P_AWS_ACCESS_KEY=$(crudini --get fargate2/config.ini AWS access_key)" >> $GITHUB_ENV
          echo "P_AWS_SECRET=$(crudini --get fargate2/config.ini AWS secret)" >> $GITHUB_ENV
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to ECR
        uses: docker/login-action@v1
        with:
          registry: ${{ env.P_DOCKER_IMAGE }}
          username: ${{ env.P_AWS_ACCESS_KEY }}
          password: ${{ env.P_AWS_SECRET }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: fargate2/
          file: fargate2/Dockerfile
          push: true
          tags: ${{ env.P_DOCKER_IMAGE }}:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}