name: ci

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Add crudini
        run: sudo apt-get install -y crudini
        run: echo "P_DOCKER_IMAGE=$(crudini --get fargate1/config.ini Docker image)" >> $GITHUB_ENV
        run: echo "P_AWS_ACCESS_KEY=$(crudini --get fargate1/config.ini AWS access_key)" >> $GITHUB_ENV
        run: echo "P_AWS_SECRET=$(crudini --get fargate1/config.ini AWS secret)" >> $GITHUB_ENV
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to ECR
        uses: docker/login-action@v1
        with:
          registry: ${{ env.P_DOCKER_IMAGE }}
          username: ${{ env.P_AWS_ACCESS_KEY }}
          password: ${{ env.P_AWS_SECRET }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: fargate1/
          file: fargate1/Dockerfile
          push: true
          tags: user/app:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}